### ISSUE TITLE
InvalidArgumentError in train.py

### ISSUE THREAD

**Issue by M4gicT0** [nywang16/Pixel2Mesh#23]
I have downloaded the training dataset, and when I run `train.py` with Python2.7, TensorFlow 1.3.0 and TFLearn 0.3.2, I get an InvalidArgumentError:

`
Traceback (most recent call last):
File "train.py", line 91, in <module>
_, dists,out1,out2,out3 = sess.run([model.opt_op,model.loss,model.output1,model.output2,model.output3], feed_dict=feed_dict)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895,in run
run_metadata_ptr)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
feed_dict_tensor, options, run_metadata)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
options, run_metadata)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,7] = -1 is not in [0, 157)
[[Node: Gather_12 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](concat_2, strided_slice_15)]]
Caused by op u'Gather_12', defined at:
File "train.py", line 37, in <module>
model = GCN(placeholders, logging=True)
File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 108, in __init__
self.build()
File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 74, in build
self._loss()
File "build/bdist.linux-x86_64/egg/pixel2mesh/models.py", line 118, in _loss
self.loss += .3*laplace_loss(self.inputs, self.output1, self.placeholders, 1)
File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 16, in laplace_loss
lap1 = laplace_coord(pred1, placeholders, block_id)
File "build/bdist.linux-x86_64/egg/pixel2mesh/losses.py", line 10, in laplace_coord
laplace = tf.reduce_sum(tf.gather(vertex, indices), 1)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2409,in gather
validate_indices=validate_indices, name=name)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1219, in gather
validate_indices=validate_indices, name=name)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py",line 767, in apply_op
op_def=op_def)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630,in create_op
original_op=self._default_original_op, op_def=op_def)
File "/code/anaconda3/envs/Pixel2Mesh/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204,in __init__
self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
InvalidArgumentError (see above for traceback): indices[0,7] = -1 is not in [0, 157)
[[Node: Gather_12 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](concat_2, strided_slice_15)]]
`

Could it be because TensorFlow seems to be using my CPU ? Do I need to install tensorflow-gpu instead of tensorflow ?

Thanks in advance

**Comment by M4gicT0** [comment]
Indeed, I just had to install the GPU version of TensorFlow.

**Comment by abadcd** [comment]
@M4gicT0 I have the same problem. Can you help me? Thank you very much.

**Comment by M4gicT0** [comment]
@abadcd 

> Indeed, I just had to install the GPU version of TensorFlow.

**Comment by abadcd** [comment]
@M4gicT0 Thank you so much, As you said, my problem has been solved.

**Comment by Weipeilang** [comment]
I  just install end the GPU version of tensorflow,but it still having this problem.

**Comment by KaePen** [comment]
Which driver version has the problem solved?

Nvidia Driver
CUDA 8.0 (8.0.44)  >= 367.48

I know the approximate driver version from CUDA8, but I would like more information.

**Comment by xiayizhan2017** [comment]
I install the GPU version of tensorflow,but it still having this problem.

**Comment by zshyang** [comment]
Hi,
Do you know how to download the dataset and unzip it from the link below?
https://drive.google.com/open?id=131dH36qXCabym1JjSmEpSQZg4dmZVQid
